[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
  nnoremap <silent> gr :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
  if executable('pt')
    let g:unite_source_grep_command = 'pt'
    let g:unite_source_grep_default_opts = '--nogroup --nocolor'
    let g:unite_source_grep_recursive_opt = ''
    let g:unite_source_grep_encoding = 'utf-8'
  endif
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
  let g:vimfiler_as_default_explorer = 1
  let g:vimfiler_edit_action = 'tabopen'
  nnoremap sf :VimFilerExplorer -find<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  imap <C-n> <C-x><C-o>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  map <C-i> :TagbarToggle<CR>
  let g:tagbar_map_togglesort = "r"
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  if isdirectory("/usr/local/opt/fzf")
    set rtp+=/usr/local/opt/fzf
  elseif isdirectory(expand("~/.fzf"))
    set rtp+=~/.fzf
  endif
  map gf :Files<CR>
'''
# see https://thinca.hatenablog.com/entry/20091009/1255059006 for "expand"

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'github/copilot.vim'
