[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby']
hook_add = '''
  command TestFile :call RunCurrentSpecFile()<CR>
  command TestHere :call RunNearestSpec()<CR>
  command TestLast :call RunLastSpec()<CR>
  command TestAll  :call RunAllSpecs()<CR>
  let g:rspec_command = 'Dispatch bundle exec rspec {spec}'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
  autocmd Filetype go nnoremap <C-]><C-]> :GoDef<CR>
  let g:go_fmt_command = "goimports"
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['javascript']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'previm/previm'
on_ft = ['md']
hook_add = '''
  let g:previm_open_cmd = 'open -a Firefox'
'''
