[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
  autocmd Filetype go nnoremap <C-]><C-]> :GoDef<CR>
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['javascript']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
